[package]
name = "riptide"
version = "0.0.1"
edition = "2021"

[dependencies]
rand = "0.8.4"
crossbeam = "0.8"
cgmath = "0.18.0"
rayon = "1.5"

[lib]
name = "riptide"
path = "src/lib.rs"

[[bin]]
name = "test_speed"
path = "src/bin/test_speed.rs"
